### ISSUE TITLE
Downloading models silently?

### ISSUE THREAD

**Issue by scruffynerf** [thoddnn/ComfyUI-MLX#7]
Please add some debugging statuses so at least the console shows files are downloading... 
You don't give urls to pre-download, so basically, the first use is a LONG wait with zero feedback.

**Comment by thoddnn** [comment]
Thanks for your feedback. It was obviously not intentional. I have pushed an update that renames the 'MLX Load Flux' node to 'MLX Load Flux Model from HF 🤗' to make it more clear. I have also added some logs to indicate when the model is downloading.

I will also be adding support for local model loading soon.
